-- AlterTable
ALTER TABLE `student` MODIFY `status` ENUM('REGISTERED', 'SUBMITTED', 'RESUBMITTED', 'UNDER_REVIEW', 'DOCUMENT_VERIFIED', 'CORRECTION_REQUIRED', 'REJECTED', 'ADMISSION_CONFIRMED', 'USN_ASSIGNED') NOT NULL DEFAULT 'REGISTERED';
